### ISSUE TITLE
Robust swagger documentation

### ISSUE THREAD

**Issue by mfenner** [datacite/sashimi#10]

**Comment by kjgarza** [comment]
Just to clarify this one. We are adding Swagger UI to the Sashimi Repo, right?
https://cloud.google.com/endpoints/docs/openapi/adding-swagger

**Comment by kjgarza** [comment]
cDone with the readme.io importer :)

**Comment by kjgarza** [comment]
https://support.datacite.org/v1.1/reference#status

**Comment by kjgarza** [comment]
review @mfenner @daslerr

**Comment by mfenner** [comment]
@kjgarza I suggest these changes:

* rename API to something that better fits the usage stats usage case
* only require authentication where needed
* not clear to me what the `status` endpoint provides
* I am not clear about the `publishers` endpoint. I would like to align this with how we do this elsewhere in DataCite (providers, clients, etc.).

**Comment by mfenner** [comment]
@kjgarza what is needed to close this?

**Comment by kjgarza** [comment]
I haven't integrated the feedback I got. So we are keeping it open for that.

**Comment by kjgarza** [comment]
please review @mfenner  

https://support.datacite.org/v1.1/reference

I removed the integration with the swagger spec. for a few reasons. 
1. you won't be able to submit json as single string.
2. report_header is not part of the report model per see and it cases problem if we submitied separatelly here. 


Right now, we have the endpoint that we need and there is more flexibility to change things without modifying the documentation. For example, adding `reporting_period`.
