### ISSUE TITLE
ERROR: No worker found for queue

### ISSUE THREAD

**Issue by mfenner** [datacite/sashimi#114]
This error is triggered by rake task `bundle exec rake reports:index`.

**Comment by mfenner** [comment]
Possibly related: https://github.com/datacite/levriero/issues/66 and https://github.com/datacite/levriero/issues/64

**Comment by kjgarza** [comment]
@mfenner  was this error present before the refactoring of the workers? https://github.com/datacite/sashimi/commit/d5b613956b9dbf711a0a9a747c96287f588dad5d

**Comment by mfenner** [comment]
yes. I think there is something wrong with the logic in ` bundle exec rake reports:index`.

**Comment by kjgarza** [comment]
More context: 

https://app.datadoghq.com/logs?cols=core_host%2Ccore_service%2Clog_ip%2Clog_network.client.ip&event&from_ts=1578391807801&index=main&live=false&messageDisplay=expanded-md&query=%40aws.awslogs.logGroup%3A%22%2Fecs%2Fmetrics-api-stage%22&stream_sort=asc&to_ts=1578392016410


https://sentry.io/organizations/datacite/issues/1397175213/?project=1462089&query=is%3Aunresolved

**Comment by kjgarza** [comment]
this is related to the delay in the queue, we need to reduce it (from 35)  and also maybe have a separate queue for usage.

**Comment by kjgarza** [comment]
proposed change:
- create a queue for report parsing. https://github.com/datacite/levriero/blob/06b0f8d0193389193b484819d0273393810b4dc1/app/jobs/usage_update_parse_job.rb#L1
- push all pending reports. We need a rake task that:
  - Push unvalidated reports (validated)

**Comment by mfenner** [comment]
That sounds good. Please go ahead. Think about the priority for the new queue.

**Comment by kjgarza** [comment]
queue has been added already

manage all the push of the unvalidated reports  in issue:
https://github.com/datacite/sashimi/issues/116
