### ISSUE TITLE
Handle older generated JWTs

### ISSUE THREAD

**Issue by kjgarza** [datacite/sashimi#131]
Some old JWT user an random ORCID in the UID field, this doesn't work with the the new authenthication model that requires UID = CLIENT_ID. We need to handle that or generate new JWT for everybody.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o15h)

**Comment by mfenner** [comment]
I suggest we give out new tokens to everyone that needs them.

**Comment by kjgarza** [comment]
JWT have been generate and sent to different clients.
if there are clients using old JWT can be identified in the **events** mysql table because they will show a serial number (looks like a orcid) in the **User_id** field rather than the **client_id**
