### ISSUE TITLE
Store uploaded files in Amazon S3 instead of the database.

### ISSUE THREAD

**Issue by svogt0511** [datacite/sashimi#133]
Store uploaded files in Amazon S3 instead of the database.

Look into using the kt-paperclip gem rather than ActiveStorage.  kt-paperclip was used in lupo for the same type of thing.  One challenge with implementing this with Rails functionality (ActiveStorage) was that we don’t have a Rails frontend and that causes problems with using JWT tokens for authentication.

Some additional info - From Kristian Garza - Proposal to deal with large report in the Hub - https://docs.google.com/document/d/1u4Ets1jJVgVQAoAa7kEaP7KaqfMzabFCAKNjZ2FvYdk/edit#heading=h.1eduajqehagp 

More of a breakdown to follow.

**Comment by svogt0511** [comment]
Last things to do before closing this issue:

* Make sure that 
    * files are backed up.
        - This is in progress.  It involves, via terraform:
             [ ] setting the versioning on the bucket.
             [ ] setting the lifecycle on previous versions of files.
    * last 6 reports export to file.  **This is done.** They are:
           0b99a0be-3683-474f-9f0c-2552e266088a
           16a1fa9d-f9e9-4373-aab2-96ae3227b44b
           1de19fae-a005-45da-adc0-bb877fbdbbf1
           3d750852-9679-4f01-bf00-fbc4a6fe1aff
           8a2c6e94-67ff-40a8-b73e-2ff8c1dc7a63
           b0cecb2c-1c7f-473e-b27b-8ae60b94cbe7
    * clean database - run the script to do this.  Takes 5 minutes.

**Comment by kjgarza** [comment]
@svogt0511 is this closed?

**Comment by svogt0511** [comment]
Closed! Will close the issue now.

Suzanne Vogt | Application Developer | DataCite
E: ***@***.*** | ORCID
W: datacite.org | Blog | Twitter | LinkedIn
Support Desk | Support Site | PID Forum

--- original message ---
On May 5, 2021, 4:19 AM EDT ***@***.*** wrote:



@svogt0511 is this closed?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by svogt0511** [comment]
Closing this.
