### ISSUE TITLE
HTTP Response 413: Request entity too large POSTing to /reports

### ISSUE THREAD

**Issue by sfisher** [datacite/sashimi#17]
This is about the test hub at https://metrics.test.datacite.org when POSTing a report to /reports.

I get a 413 response when attempting to submit the report in this ticket which is for about 24 days worth of data.  From Googling I think this might be an Nginx setting on the server.

[test_out.json.zip](https://github.com/datacite/sashimi/files/1949205/test_out.json.zip)

I needed to zip the json file to attach it in github.

**Comment by kjgarza** [comment]
we have removed the restriction now
