### ISSUE TITLE
Accepting country-counts as part of instance submissions?

### ISSUE THREAD

**Issue by sfisher** [datacite/sashimi#21]
This may be something in progress, not sure if it's implemented yet.

I saw from the meeting notes that POSTing/PUTting reports would accept country codes.

<img width="433" alt="screen shot 2018-05-11 at 10 53 00 am" src="https://user-images.githubusercontent.com/105433/39938971-943c0f32-5509-11e8-9d34-5a9315795dd0.png">

Currently getting a rejection like this when including them:

```
422
{'Date': 'Fri, 11 May 2018 17:29:39 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Status': '422 Unprocessable Entity', 'Cache-Control': 'no-cache', 'Vary': 'Accept-Encoding, Origin', 'Content-Encoding': 'gzip', 'X-Runtime': '0.413966', 'X-Request-Id': '5af22615-301d-4ccd-ae0e-081b597ae5f4', 'X-Powered-By': 'Phusion Passenger 5.2.3', 'Server': 'nginx/1.12.2 + Phusion Passenger 5.2.3'}
application/json; charset=utf-8
{
  "errors": [
    {
      "status": "422",
      "title": "found unpermitted parameters: :de, :ru"
    }
  ]
}
```
With a file like this one, which I think follows what was shown for submitting country counts.

[test_out.json.zip](https://github.com/datacite/sashimi/files/1996311/test_out.json.zip)

**Comment by kjgarza** [comment]
fixed 4b6cea4

**Comment by kjgarza** [comment]
btw country code are `keys` and thus will need to be kebab_cased. E.g. "US" will need to be sent as "us"

**Comment by kjgarza** [comment]
the report you sent me has some countries as empty strings look at line 13857
