### ISSUE TITLE
Report type endpoint does not work

### ISSUE THREAD

**Issue by kjgarza** [datacite/sashimi#37]
api.datacite.org/report-type is not working.

- it needs to have a relation to reports

**Comment by mfenner** [comment]
Why do we need a report-type API endpoint (api.datacite.org/report-type) if we use more than one report type?

**Comment by kjgarza** [comment]
It's not that we NEED it per se ist more like a MIGHT requirement of the counter spec. I suppose we can decided whether we want it or not

**Comment by kjgarza** [comment]
we do not have more work planned for MDC. I think we can close this one.
