### ISSUE TITLE
Rake task to reindex all documents

### ISSUE THREAD

**Issue by kjgarza** [datacite/sashimi#38]

**Comment by mfenner** [comment]
What is this rake task doing?

**Comment by kjgarza** [comment]
to reindex all the usage_reports .Like in lupo https://github.com/datacite/lupo/blob/660508f64c9b0e356f467967dbeddba5c983228b/lib/tasks/doi.rake#L21

**Comment by kjgarza** [comment]
closed by 1b8fa57b2f780d113cdbd358b4d4bf523c28fe65
