### ISSUE TITLE
Define access method and place for centralized user-agent list

### ISSUE THREAD

**Issue by kjgarza** [datacite/sashimi#42]
Should we have a centralised place for locating user-agents list. In the 31st October MDC meeting we discussed that this is something we all need. We also proposed some ideas. https://docs.google.com/document/d/1b7DAVm2Oqash2pF9vhLG1gN31TxtcHGF8L1vmjF8VZM/edit#

Proposal is to have a centralized list in a github repository managed by datacite. Then to set up a pull request model for contributions

- https://github.com/datacite/shiba-inu/blob/master/data/user_agents.yml
- DataONE robots list
- CDL List

We should revisit the list periodically.

**Comment by mfenner** [comment]
Closing this issue, as the user-agent list is relevant after report generation, which doesn't happen in `sashimi`, but elsewhere the step before.
